### ISSUE TITLE
Visualize the object detection results

### ISSUE THREAD

**Issue by KangchengLiu** [THU17cyz/3DIoUMatch#1]
Could you please indicate how to visualize the object detection results using generated PLY file?

**Comment by yezhen17** [comment]
Hi @KangchengLiu ,

Thanks for your interest in our work. Personally I recommend using [Meshlab](https://www.meshlab.net/) to visualize the PLY files. The visualization results in our paper are all from Meshlab.

**Comment by yezhen17** [comment]
We followed VoteNet for the visualization. Please refer to this issue in [VoteNet](https://github.com/facebookresearch/votenet/issues/3#issuecomment-525430453).

**Comment by yezhen17** [comment]
Closed due to inactivity.
