### ISSUE TITLE
Reproducing KITTI resutlts 

### ISSUE THREAD

**Issue by fnozarian** [THU17cyz/3DIoUMatch#10]
Hello,

Thank you for publishing the code and your interesting paper!
I'm trying to reproduce your results on the KITTI dataset, however, I found no code or configuration for that in your repo.
It seems that the OpenPCDet directory is untouched (wrt. original repo) and has no modifications to adapt to your framework.
Can you please explain how your current code supports KITTI via OpenPCDet?

Thanks

**Comment by yezhen17** [comment]
Hi, I will release the code soon in early June.

**Comment by rasd3** [comment]
I'm waiting for KITTI code 😭

**Comment by yezhen17** [comment]
> I'm waiting for KITTI code 😭

Just in a few days! Please stay tuned and thanks for the understanding.

**Comment by yezhen17** [comment]
@fnozarian , @rasd3 ,
The code is released! Terribly sorry for the delay, I've been stuck with other business. Check here https://github.com/THU17cyz/3DIoUMatch-PVRCNN
