### ISSUE TITLE
Test-time IoU optimization

### ISSUE THREAD

**Issue by honggyuchoi** [THU17cyz/3DIoUMatch#12]
Hello,

Thank you for your open-sourcing code and interesting paper.

I want to ask about test-time IoU optimization.
In your paper, your 3D IoU module is differentiable and it can optimize the bounding box in the test time.

<img width="379" alt="image" src="https://user-images.githubusercontent.com/42855032/127289322-fa83760b-d663-4f03-ae5c-c01020ec6f8e.png">

However, I cannot find this implemented code in your repository.
Did you release the implemented code or am i missing something?

**Comment by yezhen17** [comment]
Hi, sorry I forgot to release this part. I will release this part A.S.A.P

**Comment by yezhen17** [comment]
Just released https://github.com/THU17cyz/3DIoUMatch/commit/3d66d4885a9cbb2e578fa4f76bd8f77fbf8055e3

@honggyuchoi
