### ISSUE TITLE
Why apply softplus function on normalized size resdiuals?

### ISSUE THREAD

**Issue by Na-Z** [THU17cyz/3DIoUMatch#14]
Hi @THU17cyz,

May I know why u apply softplus function on normalized size residuals?
https://github.com/THU17cyz/3DIoUMatch/blob/8af21a4f7b43161fe9a29ec19f0a24918bbfe2aa/models/proposal_module.py#L47

How does it affect the performance?

Best,
Na

**Comment by yezhen17** [comment]
Hi @Na-Z . Thanks for your interest in our work. Actually I think it doesn't affect the performance very much, and I haven't tested with it. It is just a design choice that makes the size predicted larger than 0.
