### ISSUE TITLE
Question on points sampling

### ISSUE THREAD

**Issue by anuj-sharma-19** [THU17cyz/3DIoUMatch#16]
Hi,

First of all, thank you for the great work and sharing the code.

I have a doubt regarding the points sampling. In the paper, it is:
`
The input point clouds to our teacher network are augmented only by random sub-sampling while the inputs to the student network further undergo a set of stochastic transformation T , including random flip, random rotation around the upright axis, and a random uniform scaling.
`
Does this mean that same set of sampled points are fed into both Teacher and Student? The only difference being that after sampling, the points + boxes are augmented and then fed into Student model.

However, in the code, it seems like different sets of points are sampled for both Teacher (https://github.com/THU17cyz/3DIoUMatch/blob/1e18d3edae7a223cf6548a15b7e3a8e41d90bbcd/sunrgbd/sunrgbd_ssl_dataset.py#L242) and Student (https://github.com/THU17cyz/3DIoUMatch/blob/1e18d3edae7a223cf6548a15b7e3a8e41d90bbcd/sunrgbd/sunrgbd_ssl_dataset.py#L280). Maybe I am missing something?

Could you also please confirm if it would have any impact if same or different sets are sampled?

Thanks !!

Anuj

**Comment by yezhen17** [comment]
Hi @anuj-sharma-19 , thanks for your interest in our work!

Sorry for the confusion. We follow SESS for the point sampling and augmentation, and we did not mean the points are exactly the same set in the paper. We mean both student and teacher networks have random sampling as an augmentation, but student network input experiences more augmentation.

We have not investigated the effects if we sample the same set. This means the discrepancy between student and teacher input gets smaller, and I honestly don't know if this is a bad thing or not.

**Comment by anuj-sharma-19** [comment]
Hi @THU17cyz , thanks a lot for your clarifications !!
