### ISSUE TITLE
Some questions about your paper

### ISSUE THREAD

**Issue by qdd1234** [THU17cyz/3DIoUMatch#17]
您好，感谢您精彩的工作。我有一个问题关于iou 阈值的。就是您生成伪标签后需要通过三个指标进行过滤，其中就是有iou。但您生成的伪标签和谁做iou呢？我读完文章没能很好的理解，希望您能帮我解答一下。

**Comment by yezhen17** [comment]
您好，感谢您的关注。iou是预测得到的（与所有ground truth bounding box iou的最大值）。为了监督iou的预测，训练过程中，算出proposal和ground truth中最大的iou，作为supervision signal。

**Comment by qdd1234** [comment]
> 您好，感谢您的关注。iou是预测得到的（与所有ground truth bounding box iou的最大值）。为了监督iou的预测，训练过程中，算出proposal和ground truth中最大的iou，作为supervision signal。

感谢您的回复，可以帮我指出一下IOU预测分支的代码吗，我自己看没能很好的理解。还有supervision for IOU的代码也可以顺带指出一下吗，非常感谢您的回复！

**Comment by qdd1234** [comment]
作者您好，有一个问题想请教您一下，就是为何要在Inference阶段计算IoU estimation的梯度？不应该训练好IOU-branch之后就可以直接进行预测得到每一个预测的Bbox的iou吗？

**Comment by yezhen17** [comment]
> 作者您好，有一个问题想请教您一下，就是为何要在Inference阶段计算IoU estimation的梯度？不应该训练好IOU-branch之后就可以直接进行预测得到每一个预测的Bbox的iou吗？

inference的时候并不需要梯度呀，的确是直接每个bbox预测一个iou

**Comment by yezhen17** [comment]
> > 您好，感谢您的关注。iou是预测得到的（与所有ground truth bounding box iou的最大值）。为了监督iou的预测，训练过程中，算出proposal和ground truth中最大的iou，作为supervision signal。
> 
> 感谢您的回复，可以帮我指出一下IOU预测分支的代码吗，我自己看没能很好的理解。还有supervision for IOU的代码也可以顺带指出一下吗，非常感谢您的回复！

https://github.com/THU17cyz/3DIoUMatch/blob/1e18d3edae7a223cf6548a15b7e3a8e41d90bbcd/models/loss_helper_unlabeled.py#L536
这是从teacher模型得到iou伪标签的部分

https://github.com/THU17cyz/3DIoUMatch/blob/main/models/votenet_iou_branch.py
这是iou预测分支的代码
