### ISSUE TITLE
result of outdoor dataset

### ISSUE THREAD

**Issue by AndyYuan96** [THU17cyz/3DIoUMatch#3]
Hi，yezhen，thanks for sharing the code，I just wonder did you try the method on outdoor dataset like kitti or others。

**Comment by yezhen17** [comment]
Hi @AndyYuan96 ,

Yes, we also tried our method on KITTI with some small modifications. The paper will be updated in a few days and the code will be released soon.

**Comment by AndyYuan96** [comment]
> Hi @AndyYuan96 ,
> 
> Yes, we also tried our method on KITTI with some small modifications. The paper will be updated in a few days and the code will be released soon.

So，can I know the result，😄，does semi-supervised learning with 100% label dataset output supervised learning？I see you and sess both exceed supervised learning。

**Comment by AndyYuan96** [comment]
Hi， @THU17cyz ，I just wonder why you don't use fixmatch directly, but use a EMA of student model as teacher，rather than just use one model as in fixmatch，does EMA of student as teacher is better？

**Comment by yezhen17** [comment]
> Hi， @THU17cyz ，I just wonder why you don't use fixmatch directly, but use a EMA of student model as teacher，rather than just use one model as in fixmatch，does EMA of student as teacher is better？

Although we didn't include that in our experiments section, using EMA of student as teacher is indeed better.

**Comment by yezhen17** [comment]
> > Hi @AndyYuan96 ,
> > Yes, we also tried our method on KITTI with some small modifications. The paper will be updated in a few days and the code will be released soon.
> 
> So，can I know the result，😄，does semi-supervised learning with 100% label dataset output supervised learning？I see you and sess both exceed supervised learning。

Yes, it also outperforms supervised training on KITTI. We experimented on 1%, 2% and 100% labeled data and the performance is generally consistent with that on ScanNet and SUNRGBD. The paper will be updated in a few days. The analysis on why our method also works when we have 100% labeled data is beyond the scope of our paper, but we believe it might be similar to the effect of knowledge distillation (you can read [this paper](https://openaccess.thecvf.com/content_CVPR_2020/papers/Yuan_Revisiting_Knowledge_Distillation_via_Label_Smoothing_Regularization_CVPR_2020_paper.pdf)).

**Comment by AndyYuan96** [comment]
thanks for sharing the result。

**Comment by yezhen17** [comment]
The latest version of the paper: https://arxiv.org/pdf/2012.04355v2.pdf

**Comment by AndyYuan96** [comment]
> The latest version of the paper: https://arxiv.org/pdf/2012.04355v2.pdf

many thanks for quickly update，when the kitti code will be released，I want to try on my dataset。

**Comment by yezhen17** [comment]
> > The latest version of the paper: https://arxiv.org/pdf/2012.04355v2.pdf
> 
> many thanks for quickly update，when the kitti code will be released，I want to try on my dataset。

Sorry, I'm too busy to release the code now. The logic is similar to this repo so I believe you can just refer to this repo for now?

**Comment by AndyYuan96** [comment]
> > > The latest version of the paper: https://arxiv.org/pdf/2012.04355v2.pdf
> > 
> > 
> > many thanks for quickly update，when the kitti code will be released，I want to try on my dataset。
> 
> Sorry, I'm too busy to release the code now. The logic is similar to this repo so I believe you can just refer to this repo for now?

ok，I will give it a try

**Comment by AndyYuan96** [comment]
> > > The latest version of the paper: https://arxiv.org/pdf/2012.04355v2.pdf
> > 
> > 
> > many thanks for quickly update，when the kitti code will be released，I want to try on my dataset。
> 
> Sorry, I'm too busy to release the code now. The logic is similar to this repo so I believe you can just refer to this repo for now?

Hi, Yezhen, what's the weak augmentation that you use in kitti dataset with pvrcnn?

**Comment by yezhen17** [comment]
> > > > The latest version of the paper: https://arxiv.org/pdf/2012.04355v2.pdf
> > > 
> > > 
> > > many thanks for quickly update，when the kitti code will be released，I want to try on my dataset。
> > 
> > 
> > Sorry, I'm too busy to release the code now. The logic is similar to this repo so I believe you can just refer to this repo for now?
> 
> Hi, Yezhen, what's the weak augmentation that you use in kitti dataset with pvrcnn?

Similar to that in ScanNet and SUNRGBD, you can just discard the flip, rotation and scaling in the weaker augmentation.

**Comment by baraujo98** [comment]
> > > > The latest version of the paper: https://arxiv.org/pdf/2012.04355v2.pdf
> > > 
> > > 
> > > many thanks for quickly update，when the kitti code will be released，I want to try on my dataset。
> > 
> > 
> > Sorry, I'm too busy to release the code now. The logic is similar to this repo so I believe you can just refer to this repo for now?
> 
> ok，I will give it a try

@AndyYuan96 would you be willing to share your fork of 3DIoUMatch? I'm very curious to experiment with this framework on KITTI. If you did not start the code adaptation yet, no problem. I'm thinking of doing it this week, anyways, and I can share the process with you, if you want.
