### ISSUE TITLE
filtering mechanism on SESS does not achieve good results

### ISSUE THREAD

**Issue by yyuxin** [THU17cyz/3DIoUMatch#6]
Hi, Thank you for sharing such great work! 
As far as I understand, 3DIoUMatch is a filtering mechanism on sess.

But I try to filter on sess by setting the threshold of score and objectness, the effect is not good, do you know what is the reason?
The thresholds are selected as 0.9.

**Comment by yezhen17** [comment]
Hi @yyuxin,

We are not simply filtering upon SESS. For one thing, we do not supervise every proposal from the student model like SESS. 

I don't know how you modified SESS so I have no clue. Maybe you can compare your implementation with our code?

**Comment by yyuxin** [comment]
If we don't consider 3D IoU, the difference with sess is
SESS:  128 proposals from teacher network, students also have 128 proposals, do consistency loss

Then 3DIoUMatch：The 128 proposals from teacher network, after filtering, only some high quality  are left, and 128 proposals from student, do loss
Do I understand correctly?

**Comment by yezhen17** [comment]
Yes, this covers most of the difference except our IoU module-based operations. I think the difference between the losses is crucial to the performance gap.

**Comment by hughw19** [comment]
One key difference to blindly supervise consistency: we perform selective
supervision ( see the relevant section for more details). This is very
important for our performance.

**Comment by yyuxin** [comment]
got it! Thanks for your patient reply.
