### ISSUE TITLE
Environment

### ISSUE THREAD

**Issue by yjh576** [THU17cyz/3DIoUMatch#8]
When torch_version==1.3.0 OpenPCDet  reports an error: 

    from models.votenet_iou_branch import VoteNet
  File "/home/point/3DIoUMatch/models/votenet_iou_branch.py", line 17, in <module>
    from models.backbone_module import Pointnet2Backbone
  File "/home/point/3DIoUMatch/models/backbone_module.py", line 19, in <module>
    from pointnet2_modules import PointnetSAModuleVotes, PointnetFPModule
  File "/home/point/3DIoUMatch/pointnet2/pointnet2_modules.py", line 26, in <module>
    import pointnet2_utils
  File "/home/point/3DIoUMatch/pointnet2/pointnet2_utils.py", line 31, in <module>
    "Could not import _ext module.\n"
ImportError: Could not import _ext module.
Please see the setup instructions in the README: https://github.com/erikwijmans/Pointnet2_PyTorch/blob/master/README.rst

When torch_version==1.5.1, pointnet2  reports an error: 

    import pointnet2._ext as _ext
ModuleNotFoundError: No module named 'pointnet2._ext'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/point/3DIoUMatch/pointnet2/pointnet2_utils.py", line 27, in <module>
    import pointnet2_ops._ext as _ext
ModuleNotFoundError: No module named 'pointnet2_ops'

Could you  give me adivice?  thanks!

**Comment by yezhen17** [comment]
Hi @yjh576 ,

I don't think OpenPCDet is involved. Did you successful install pointnet2 as instructed [here](https://github.com/THU17cyz/3DIoUMatch#installation)?

**Comment by yjh576** [comment]
Yes, I install it step by step according to readme.txt

**Comment by yezhen17** [comment]
If you switched to torch 1.5 after first installing pointnet2 with torch 1.3, maybe you can try
```
rm -rf ./build
find . -name "*.so" | xargs rm
```

under the pointnet2 folder, and then reinstall pointnet2.

If it still fails, maybe you can install pointnet2 from the original [repo](https://github.com/erikwijmans/Pointnet2_PyTorch/blob/master/README.rst#building-only-the-cuda-kernels) and skip installing it from the pointnet2 folder.
