### ISSUE TITLE
About the environment 

### ISSUE THREAD

**Issue by WangZhouTao** [THU17cyz/3DIoUMatch#9]
Thank you for sharing your code.
I follow the instructions in readme.txt and install all the packages.
When I tried to run the following command:
`sh run_pretrain.sh 0 pretrain_scannet scannet scannetv2_train_0.1.txt`
I encountered this error:
`Traceback (most recent call last):
  File "pretrain.py", line 24, in <module>
    from models.loss_helper_labeled import get_labeled_loss
  File "/home/logic/m2/project/3DIOU/3DIoUMatch/models/loss_helper_labeled.py", line 14, in <module>
    from models.loss_helper_iou import compute_iou_labels
  File "/home/logic/m2/project/3DIOU/3DIoUMatch/models/loss_helper_iou.py", line 11, in <module>
    from utils.box_util import box3d_iou_batch_gpu, box3d_iou_gpu_axis_aligned
  File "/home/logic/m2/project/3DIOU/3DIoUMatch/utils/box_util.py", line 20, in <module>
    raise ImportError("please first install pcdet according to README.md")
ImportError: please first install pcdet according to README.md
`
Have you encountered a similar problem, or can you provide a solution?
Looking forward to your reply.

**Comment by yezhen17** [comment]
Hi @WangZhouTao ,

Have you successfully installed OpenPCDet?

**Comment by yezhen17** [comment]
Closed due to inactivity.
